FROM node:18-alpine as builder

ENV NODE_ENV build

WORKDIR /usr/app

COPY ../ .

RUN npm ci && npm run build && npm prune --production

COPY ../package*.json .

FROM node:18-alpine

ENV NODE_ENV production

WORKDIR /usr/app

COPY --from=builder /usr/app/package*.json .
COPY --from=builder /usr/app/node_modules/ ./node_modules
COPY --from=builder /usr/app/dist ./dist

EXPOSE 3333

CMD ["node", "dist/main.js"]