version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - .:/usr/app/.data/data/db
    ports:
      - '27017:27017'
    logging:
      driver: none
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGO_URI}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWD}
    networks:
      - app-network

  app:
    container_name: teste_workmize
    restart: always
    env_file:
      - .env
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    depends_on:
      - mongodb
networks:
  app-network:
